version: '3.1'
services:
  sboot-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=emregltkn
      - RABBITMQ_DEFAULT_PASS=pass1234