version: '3.1'
services:
  gltkn-kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: localhost
    container_name: gltkn-kafka
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"